name: CI

on: { push: { branches: '**' } }

jobs:
  ci:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        # fetch full history for correct commits parsing in tests
        with: { fetch-depth: 0 }

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with: { version: latest }

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with: { node-version: latest, cache: pnpm }

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build:prod

      - name: Lint
        run: pnpm lint:fix