name: Release

on: { push: { tags: 'v[0-9]+.[0-9]+.[0-9]+*' } }

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # for creating a GitHub release
      id-token: write # for publishing to npm with provenance
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main # attach HEAD to 'main' to avoid pnpm publish error ERR_PNPM_GIT_UNKNOWN_BRANCH
          fetch-depth: 0 # fetch full history for correct commits parsing

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with: { version: 10.25.0 }

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with: { node-version: 24.11.1, cache: pnpm, registry-url: https://registry.npmjs.org }

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build:prod

      - name: Lint
        run: pnpm lint:fix

      - name: Test
        run: pnpm test

      - name: Create release archive
        run: |
          ARCHIVE_NAME=${GITHUB_REPOSITORY##*/}-$TAG.zip
          echo ARCHIVE_NAME=$ARCHIVE_NAME >> $GITHUB_ENV
          zip -r $ARCHIVE_NAME dist package.json LICENSE README.md

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $TAG \
            --title $TAG \
            --notes "$(pnpm --silent release:github)" \
            --draft \
            $ARCHIVE_NAME

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --provenance